# common properties
spring:
  application:
    name: sorface-sso
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
    cors:
      configs:
        - pattern: /**
          allowed-origins: "http://127.0.0.1:8080,http://localhost:5043"
          allowed-headers: "*"
          exposed-headers: "*"
          allowed-methods: "*"
          allow-credentials: true
  web:
    resources:
      static-locations: classpath:static

  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:8080
        introspection-endpoint: /oauth2/token-info
      client:
        registration:
          github:
            client-name: github
            client-id: 43794d53ae6c719cfa3d
            client-secret: 5c7ea6108598e249b56dc9784e31c4b05b542d98
          google:
            client-name: google
            clientId: 574812042094-9t4sbk2hc7cr6q9hapdcg6edd5no56gd.apps.googleusercontent.com
            clientSecret: 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
            authorization-grant-type: authorization_code
          yandex:
            client-name: yandex
            client-id: ee1bdcc325294d8a915db0ede6911b85
            client-secret: 0598eae2d4b1495f9b0b7d5923b11913
            authorization-grant-type: authorization_code
            provider: yandex
            redirect-uri: http://localhost:8080/login/oauth2/code/yandex
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info
      resourceserver:
        opaquetoken:
          introspection-uri: "/oauth2/introspect"
          client-id: charp
          client-secret: password

  mail:
    username: welcome@sorface.com
    password: nphnsnxgcimstkxj
    port: 465
    host: smtp.yandex.ru
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

logging:
  level:
    "liquibase": error

# development
---
spring:
  config:
    activate:
      on-profile: development

  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:8888
  web:
    resources:
      static-locations: classpath:static

  session:
    timeout: 1800
    redis:
      flush-mode: on_save
      namespace: sorface:session
      save-mode: on_set_attribute

  data:
    redis:
      client-type: lettuce
      database: 0
      host: localhost
      port: 6379
      password: qwerty
      lettuce:
        pool:
          max-active: 16
          max-idle: 8

  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:file:./sorface-sso;AUTO_SERVER=TRUE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

sorface:
  sso:
    token:
      format: REFERENCE
      access-time-live: 30
      refresh-time-live: 120
      reuse-refresh-token: false
      authorization-code-time-live: 30

logging:
  level:
    root: DEBUG
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.security: TRACE
#    logging.level.org.hibernate.SQL: INFO
#    com.zaxxer.hikari: ERROR
#    org.postgresql: ERROR

---
spring:
  config:
    activate:
      on-profile: docker

  web:
    resources:
      static-locations: classpath:static
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:8888
        introspection-endpoint: /oauth2/token-info
      client:
        registration:
          github:
            client-name: github
            client-id: 43794d53ae6c719cfa3d
            client-secret: 5c7ea6108598e249b56dc9784e31c4b05b542d98
            redirect-uri: http://localhost:8888/login/oauth2/code/github
          google:
            client-name: google
            clientId: 574812042094-9t4sbk2hc7cr6q9hapdcg6edd5no56gd.apps.googleusercontent.com
            clientSecret: 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
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8888/login/oauth2/code/google
          yandex:
            client-name: yandex
            client-id: ee1bdcc325294d8a915db0ede6911b85
            client-secret: 0598eae2d4b1495f9b0b7d5923b11913
            authorization-grant-type: authorization_code
            provider: yandex
            redirect-uri: http://localhost:8888/login/oauth2/code/yandex
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info

  session:
    timeout: 1800
    redis:
      flush-mode: on_save
      namespace: sorface:session
      save-mode: on_set_attribute

  data:
    redis:
      client-type: lettuce
      database: 0
      host: redis
      port: 6379
      password: qwerty
      lettuce:
        pool:
          max-active: 16
          max-idle: 8

  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:file:./sorface-sso;AUTO_SERVER=TRUE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

sorface:
  sso:
    token:
      format: REFERENCE
      access-time-live: 30
      refresh-time-live: 120
      reuse-refresh-token: false
      authorization-code-time-live: 30

logging:
  level:
    root: INFO
---

# production
spring:
  config:
    activate:
      on-profile: production

  jpa:
    show-sql: true
    database: postgresql

  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username: <postgres_username>
    password: <postgres_password>