# common properties
spring:
  application:
    name: sorface-sso
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:8080
        introspection-endpoint: /oauth2/token-info
      client:
        registration:
          github:
            client-name: github
            client-id: <github_id>
            client-secret: <github_secret>
          google:
            client-name: google
            clientId: <client_id>
            clientSecret: <client_secret>
            authorization-grant-type: authorization_code
          yandex:
            client-name: yandex
            client-id: <yandex_id>
            client-secret: <yandex_secret>
            authorization-grant-type: authorization_code
            provider: yandex
            redirect-uri: http://localhost:8080/login/oauth2/code/yandex
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info

  mail:
    username: <username_email>
    password: <email_password>
    port: 465
    host: <smtp.host.com>
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

logging:
  level:
    "liquibase" : error

# development
---
spring:
  config:
    activate:
      on-profile: development

  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:file:./sorface-sso;AUTO_SERVER=TRUE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

sorface:
  sso:
    token:
      format: REFERENCE
      access-time-live: 30
      refresh-time-live: 120
      reuse-refresh-token: false
      authorization-code-time-live: 30

logging:
  level:
    org.springframework.security.oauth2: debug
    com.zaxxer.hikari: warn
    root: trace
---

# production
spring:
  config:
    activate:
      on-profile: production

  jpa:
    show-sql: true
    database: postgresql

  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username: <postgres_username>
    password: <postgres_password>