version: '3.9'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - redis-stack-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - "6379:6379"
    env_file:
      - .docker.redis.env

  postgresql:
    container_name: "postgres"
    build:
      context: .
      dockerfile: postgresql/Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .docker.pgsql.env

  sso:
    container_name: "sso-sorface"
    build:
      context: ../
      dockerfile: docker/sso/Dockerfile
    depends_on:
      - redis
      - postgresql
    ports:
      - '8888:8080'
    env_file:
      - .docker.sso.env