version: '3.9'

networks:
  a-center:
    external: true

# docker network create --driver=bridge --subnet=172.28.0.0/16 --ip-range=172.28.5.0/24 --gateway=172.28.5.254 a-center

services:
  redis:
    container_name: "redis"

    build:
      context: .
      dockerfile: redis/Dockerfile
    restart: unless-stopped
    ports:
      - "6379:6379"
    env_file:
      - .docker.redis.env
    hostname: redis.net

  postgresql:
    container_name: "postgres"

    build:
      context: postgresql
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .docker.pgsql.env

  sorface.security:
    container_name: "sorface.security"

    build:
      context: ../
      dockerfile: docker/sso/Dockerfile
    restart: always

    depends_on:
      - redis
      - postgresql
    env_file:
      - .docker.sorface.sso.backend.env

  sorface.security.proxy:
    container_name: "sorface.security.proxy"
    build:
      context: ../
      dockerfile: docker/proxy/Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080
        - REACT_APP_VERSION=1.0.0-Docker
        - NGINX_DOMAIN=localhost
        - NGINX_SECURITY_BACKEND_URL=http://sorface.security:8080
    ports:
      - "8080:80"
