# common properties

spring:
  application:
    name: sorface-sso

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    static-path-pattern: /static/**

    endpoint:
      uri-page-signin: '/account/signin'
      uri-page-signup: '/account/signup'
      uri-page-not-found: '/account/404'
      uri-page-profile: '/account'
      uri-api-login: "/api/accounts/signin"
      uri-api-logout: "/api/accounts/logout"

  web:
    resources:
      static-locations: classpath:static

  redis:
    sorface:
      auth:
        complete-prefix: 'oauth2_auth_complete:'
        init-prefix: 'oauth2_auth_init:'
        ttl: 72000

  security:
    oauth2:
      client:
        registration:
          github:
            client-name: github
            client-id: ${OAUTH_CLIENT_GITHUB_ID}
            client-secret: ${OAUTH_CLIENT_GITHUB_SECRET}
          google:
            client-name: google
            clientId: ${OAUTH_CLIENT_GOOGLE_ID}
            clientSecret: ${OAUTH_CLIENT_GOOGLE_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          yandex:
            client-name: yandex
            client-id: ${OAUTH_CLIENT_YANDEX_ID}
            client-secret: ${OAUTH_CLIENT_YANDEX_SECRET}
            authorization-grant-type: authorization_code
            provider: yandex
            redirect-uri: ${OAUTH_CLIENT_YANDEX_REDIRECT_URL}
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info
      resourceserver:
        opaquetoken:
          introspection-uri: "/oauth2/introspect"
          client-id: charp
          client-secret: password

    sorface:
      sso:
        issuer-url: ${OAUTH_SERVER_ISSUER_URL}

  mail:
    username: ${MAIL_NOTIFICATOR_USERNAME}
    password: ${MAIL_NOTIFICATOR_PASSWORD}
    port: 465
    host: smtp.yandex.ru
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true

  session:
    timeout: 1800
    redis:
      flush-mode: on_save
      namespace: sorface:session
      save-mode: on_set_attribute

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

  data:
    redis:
      client-type: jedis
      database: 0
      host: ${REDIS_HOST}
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
