# local.docker
server:
  port: 8080

sorface:
  cookie:
    session:
      same-site: lax
  cors:
    options:
      - pattern: /**
        allowed-origins: ${CLIENT_SERVER_DOMAIN}, http://localhost:3000, http://127.0.0.1:3000
        allowed-headers: "*"
        allowed-methods: "*"
        exposed-headers: "*"
        allow-credentials: true
        max-age: 3600

spring:
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
    hikari:
      connection-timeout: 30000
      connection-test-query: select 1
      maximum-pool-size: 10
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      pool-name: "HikariPool-sso"
      register-mbeans: true

  liquibase:
    contexts: development

logging:
  level:
    root: info
    nl.basjes.parse: error
    org.springframework.security.web: error
