# development
server:
  port: 8080

spring:
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.h2.Driver

logging:
  level:
    root: info