# common properties
sorface:
  client:
    domain: ${CLIENT_SERVER_DOMAIN}

  cors:
    options:
      - pattern: /**
        allowed-origins: ${CLIENT_SERVER_DOMAIN}, http://localhost:8080, http://127.0.0.1:8085, http://localhost:8085
        allowed-headers: "*"
        allowed-methods: "*"
        exposed-headers: "*"
        allow-credentials: true
      - pattern: /v3/api-docs
        allowed-origins: "http://localhost:8085"
        allowed-headers: "*"
        exposed-headers: "*"
        allowed-methods: "*"
        allow-credentials: true
  cookie:
    session:
      domain-pattern: '^.+?\.(\w+\.[a-z]+)$'
      path: '/'
      name: 'JSESSIONID'
      http-only: true
    csrf:
      domain: 'localhost'
      path: '/'
      name: 'x_csrf_token'
      http-only: true

  endpoint:
    uri-page-signin: '${sorface.client.domain}/account/signin'
    uri-page-signup: '${sorface.client.domain}/account/signup'
    uri-page-not-found: '${sorface.client.domain}/account/404'
    uri-page-profile: '${sorface.client.domain}/account'
    uri-page-failure: "${sorface.client.domain}/failure"
    uri-api-login: "/api/accounts/signin"
    uri-api-logout: "/api/accounts/logout"

  oauth2:
    issuer-url: ${OAUTH_SERVER_ISSUER_URL}
    redis:
      complete-prefix: 'oauth2_auth_complete:'
      init-prefix: 'oauth2_auth_init:'
      ttl: 72000

spring:
  application:
    name: sorface-sso

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  mvc:
    static-path-pattern: /static/**

  web:
    resources:
      static-locations: classpath:static

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

  security:
    oauth2:
      client:
        registration:
          github:
            client-name: github
            client-id: ${OAUTH_CLIENT_GITHUB_ID}
            client-secret: ${OAUTH_CLIENT_GITHUB_SECRET}
          google:
            client-name: google
            clientId: ${OAUTH_CLIENT_GOOGLE_ID}
            clientSecret: ${OAUTH_CLIENT_GOOGLE_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          yandex:
            client-name: yandex
            client-id: ${OAUTH_CLIENT_YANDEX_ID}
            client-secret: ${OAUTH_CLIENT_YANDEX_SECRET}
            authorization-grant-type: authorization_code
            provider: yandex
            redirect-uri: ${OAUTH_CLIENT_YANDEX_REDIRECT_URL}
          twitch:
            client-name: twitch
            client-id: ${OAUTH_CLIENT_TWITCH_ID}
            client-secret: ${OAUTH_CLIENT_TWITCH_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - user:read:email
            provider: twitch
            redirect-uri: ${OAUTH_CLIENT_TWITCH_REDIRECT_URL}
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info
          twitch:
            authorization-uri: https://id.twitch.tv/oauth2/authorize
            token-uri: https://id.twitch.tv/oauth2/token
            userInfoUri: https://api.twitch.tv/helix/users/
            user-info-authentication-method: GET
            user-name-attribute: data

  mail:
    username: ${MAIL_NOTIFICATOR_USERNAME}
    password: ${MAIL_NOTIFICATOR_PASSWORD}
    port: 465
    host: smtp.yandex.ru
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true

  session:
    timeout: 1800
    redis:
      flush-mode: on_save
      namespace: sorface:session
      save-mode: on_set_attribute
      repository-type: indexed

  data:
    redis:
      client-type: lettuce
      database: 0
      host: ${REDIS_HOST}
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 16
          max-idle: 8