name: yc.deploy.image wd [release]

on:
  workflow_dispatch:
    inputs:
      release-tag:
        required: true
        type: string
    
    secrets:
      YC_ACCOUNT:
        required: true
      DATABASE_PASSWORD:
        required: true
      DATABASE_URL:
        required: true
      DATABASE_USERNAME:
        required: true
      MAIL_NOTIFICATOR_PASSWORD:
        required: true
      MAIL_NOTIFICATOR_USERNAME:
        required: true
      OAUTH_CLIENT_GITHUB_ID:
        required: true
      OAUTH_CLIENT_GITHUB_SECRET:
        required: true
      OAUTH_CLIENT_GOOGLE_ID:
        required: true
      OAUTH_CLIENT_GOOGLE_SECRET:
        required: true
      OAUTH_CLIENT_TWITCH_ID:
        required: true
      OAUTH_CLIENT_TWITCH_SECRET:
        required: true
      OAUTH_CLIENT_YANDEX_ID:
        required: true
      OAUTH_CLIENT_YANDEX_SECRET:
        required: true
      REDIS_PASSWORD:
        required: true
      REDIS_USERNAME:
        required: true

jobs:
  redis-stack:
    name: build redis-stack
    uses: sorface/sso-server/.github/workflows/yc-docker-image-workflow-call.yml@master
    with:
      release-tag: ${{ github.event.inputs.release-tag }}
      name: platform-sso
      OAUTH_CLIENT_TWITCH_REDIRECT_URL: ${{ vars.OAUTH_CLIENT_TWITCH_REDIRECT_URL }}
      OAUTH_CLIENT_YANDEX_REDIRECT_URL: ${{ vars.OAUTH_CLIENT_YANDEX_REDIRECT_URL }}
      OAUTH_SERVER_ISSUER_URL: ${{ vars.OAUTH_SERVER_ISSUER_URL }}
      REDIS_HOST: ${{ vars.REDIS_HOST }}
    secrets:
      YC_ACCOUNT: ${{ secrets.YC_ACCOUNT }}

      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      MAIL_NOTIFICATOR_PASSWORD: ${{ secrets.MAIL_NOTIFICATOR_PASSWORD }}
      MAIL_NOTIFICATOR_USERNAME: ${{ secrets.MAIL_NOTIFICATOR_USERNAME }}
      OAUTH_CLIENT_GITHUB_ID: ${{ secrets.OAUTH_CLIENT_GITHUB_ID }}
      OAUTH_CLIENT_GITHUB_SECRET: ${{ secrets.OAUTH_CLIENT_GITHUB_SECRET }}
      OAUTH_CLIENT_GOOGLE_ID: ${{ secrets.OAUTH_CLIENT_GOOGLE_ID }}
      OAUTH_CLIENT_GOOGLE_SECRET: ${{ secrets.OAUTH_CLIENT_GOOGLE_SECRET }}
      OAUTH_CLIENT_TWITCH_ID: ${{ secrets.OAUTH_CLIENT_TWITCH_ID }}
      OAUTH_CLIENT_TWITCH_SECRET: ${{ secrets.OAUTH_CLIENT_TWITCH_SECRET }}
      OAUTH_CLIENT_YANDEX_ID: ${{ secrets.OAUTH_CLIENT_YANDEX_ID }}
      OAUTH_CLIENT_YANDEX_SECRET: ${{ secrets.OAUTH_CLIENT_YANDEX_SECRET }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
